trigger:
- master

pool:
  vmImage: ubuntu-latest

  # This determines the build number
name: $(MajorMinorVersion)$(Rev:.r)

steps:
- task: Npm@1
  displayName: 'Set the version'
  inputs:
    command: custom
    customCommand: version $(Build.Buildnumber) --no-git-tag-version
    workingDir: 'projects/angular-building-blocks'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'

- task: Npm@1
  displayName: 'Build the library'
  inputs:
    command: 'custom'
    customCommand: 'run build'

- task: Npm@1
  displayName: 'Publish the library'
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: 8f8fdedc-8dad-4678-a7ed-dbaa55d4b955/enigmatry-feed
    workingDir: 'dist'

