trigger:
- master

pool:
  vmImage: ubuntu-latest

  # This determines the build number
name: $(MajorMinorVersion)$(Rev:.r)

steps:
- task: Npm@1
  displayName: 'Set the version angular-building-blocks'
  inputs:
    command: custom
    customCommand: version $(Build.Buildnumber) --no-git-tag-version
    workingDir: 'projects/angular-building-blocks'

- task: Npm@1
  displayName: 'Set the version qti-rendering'
  inputs:
    command: custom
    customCommand: version $(Build.Buildnumber) --no-git-tag-version
    workingDir: 'projects/qti-rendering'

- task: Npm@1
  displayName: 'Set the version eslint recommended rules'
  inputs:
    command: custom
    customCommand: version $(Build.Buildnumber) --no-git-tag-version
    workingDir: 'projects/eslint-config'
    
- task: Npm@1
  displayName: 'Set the version stylelint recommended rules'
  inputs:
    command: custom
    customCommand: version $(Build.Buildnumber) --no-git-tag-version
    workingDir: 'projects/stylelint-config'

- task: Npm@1
  displayName: 'Set the version scss foundation'
  inputs:
    command: custom
    customCommand: version $(Build.Buildnumber) --no-git-tag-version
    workingDir: 'projects/scss-foundation'

- task: Npm@1
  displayName: 'Set the version formly-extensions'
  inputs:
    command: custom
    customCommand: version $(Build.Buildnumber) --no-git-tag-version
    workingDir: 'projects/formly-extensions'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
    
- task: Npm@1
  displayName: 'npm install scss foundation'
  inputs:
    command: 'install'
    workingDir: 'projects/scss-foundation'
    
- task: Npm@1
  displayName: 'Test the scss foundation library'
  inputs:
    command: 'custom'
    customCommand: 'run test'
    workingDir: 'projects/scss-foundation'

- task: Npm@1
  displayName: 'Build the angular-building-blocks library'
  inputs:
    command: 'custom'
    customCommand: 'run build angular-building-blocks'

- task: Npm@1
  displayName: 'Build the qti-rendering library'
  inputs:
    command: 'custom'
    customCommand: 'run build qti-rendering'
    
- task: Npm@1
  displayName: 'Build the scss foundation library'
  inputs:
    command: 'custom'
    customCommand: 'run build'
    workingDir: 'projects/scss-foundation'

- task: Npm@1
  displayName: 'Build the formly-extensions library'
  inputs:
    command: 'custom'
    customCommand: 'run build formly-extensions'

- task: Npm@1
  displayName: 'Publish the angular-building-blocks library'
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: enigmatry
    workingDir: 'dist/angular-building-blocks'

- task: Npm@1
  displayName: 'Publish the qti-rendering library'
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: enigmatry
    workingDir: 'dist/qti-rendering'

- task: Npm@1
  displayName: 'Publish the eslint recommended rules'
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: enigmatry
    workingDir: 'projects/eslint-config'

- task: Npm@1
  displayName: 'Publish the stylelint recommended rules'
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: enigmatry
    workingDir: 'projects/stylelint-config'
    
- task: Npm@1
  displayName: 'Publish the scss foundation'
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: enigmatry
    workingDir: 'projects/scss-foundation'

- task: Npm@1
  displayName: 'Publish the formly-extensions library'
  inputs:
    command: publish
    publishRegistry: useFeed
    publishFeed: enigmatry
    workingDir: 'dist/formly-extensions'
